name: Cloudflare Pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: rustup update
      - run: cargo install trunk
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup --version
      - run: cargo --version
      - run: trunk --version
      - run: trunk build --release
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: 'my-first-rust-sample'
          directory: './dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
